FROM httpd

# set the present directory in image to the given directory
WORKDIR /usr/local/apache2/htdocs

# COPY index.html .
# COPY file1.html .
# COPY file2.html .

# copy all the files and sub directories present in the 
# current working directory (local) to 
# the current working directory of the image
# COPY . /usr/local/apache2/htdocs
COPY . .